from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class livegames(models.Model):
    Team1A = models.CharField(max_length=50)
    Team1B = models.CharField(max_length=50)
    Team2A = models.CharField(max_length=50) 
    Team2B = models.CharField(max_length=50)
    Team3A = models.CharField(max_length=50)
    Team3B = models.CharField(max_length=50)
    Team4A = models.CharField(max_length=50)
    Team4B = models.CharField(max_length=50)
    Team5A = models.CharField(max_length=50)
    Team5B = models.CharField(max_length=50)
    Team6A = models.CharField(max_length=50)
    Team6B = models.CharField(max_length=50)
    Team7A = models.CharField(max_length=50)
    Team7B = models.CharField(max_length=50)
    Team8A = models.CharField(max_length=50)
    Team8B = models.CharField(max_length=50)
    Team9A = models.CharField(max_length=50)
    Team9B = models.CharField(max_length=50)

class userwerte(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    wertT1A = models.IntegerField(default=0)
    wertT1B = models.IntegerField(default=0)
    wertT2A = models.IntegerField(default=0)
    wertT2B = models.IntegerField(default=0)
    wertT3A = models.IntegerField(default=0)
    wertT3B = models.IntegerField(default=0)
    wertT4A = models.IntegerField(default=0)
    wertT4B = models.IntegerField(default=0)
    wertT5A = models.IntegerField(default=0)
    wertT5B = models.IntegerField(default=0)
    wertT6A = models.IntegerField(default=0)
    wertT6B = models.IntegerField(default=0)
    wertT7A = models.IntegerField(default=0)
    wertT7B = models.IntegerField(default=0)
    wertT8A = models.IntegerField(default=0)
    wertT8B = models.IntegerField(default=0)
    wertT9A = models.IntegerField(default=0)
    wertT9B = models.IntegerField(default=0)
    aktiv = models.BooleanField(default=True)