# Generated by Django 5.2.5 on 2025-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TippIt', '0002_delete_benutzer'),
    ]

    operations = [
        migrations.CreateModel(
            name='livegames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1A', models.CharField(max_length=50)),
                ('Team1B', models.CharField(max_length=50)),
                ('Team2A', models.CharField(max_length=50)),
                ('Team2B', models.CharField(max_length=50)),
                ('Team3A', models.CharField(max_length=50)),
                ('Team3B', models.CharField(max_length=50)),
                ('Team4A', models.CharField(max_length=50)),
                ('Team4B', models.CharField(max_length=50)),
                ('Team5A', models.CharField(max_length=50)),
                ('Team5B', models.CharField(max_length=50)),
                ('Team6A', models.CharField(max_length=50)),
                ('Team6B', models.CharField(max_length=50)),
                ('Team7A', models.CharField(max_length=50)),
                ('Team7B', models.CharField(max_length=50)),
                ('Team8A', models.CharField(max_length=50)),
                ('Team8B', models.CharField(max_length=50)),
                ('Team9A', models.CharField(max_length=50)),
                ('Team9B', models.CharField(max_length=50)),
            ],
        ),
    ]
