# Generated by Django 5.2.5 on 2025-08-23 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TippIt', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userwerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wertT1A', models.IntegerField(default=0)),
                ('wertT1B', models.IntegerField(default=0)),
                ('wertT2A', models.IntegerField(default=0)),
                ('wertT2B', models.IntegerField(default=0)),
                ('wertT3A', models.IntegerField(default=0)),
                ('wertT3B', models.IntegerField(default=0)),
                ('wertT4A', models.IntegerField(default=0)),
                ('wertT4B', models.IntegerField(default=0)),
                ('wertT5A', models.IntegerField(default=0)),
                ('wertT5B', models.IntegerField(default=0)),
                ('wertT6A', models.IntegerField(default=0)),
                ('wertT6B', models.IntegerField(default=0)),
                ('wertT7A', models.IntegerField(default=0)),
                ('wertT7B', models.IntegerField(default=0)),
                ('wertT8A', models.IntegerField(default=0)),
                ('wertT8B', models.IntegerField(default=0)),
                ('wertT9A', models.IntegerField(default=0)),
                ('wertT9B', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
