# Generated by Django 5.2.5 on 2025-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TippIt', '0004_userwerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwerte',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
    ]
