# Generated by Django 5.2.5 on 2025-08-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TippIt', '0005_userwerte_aktiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwerte',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
